### ISSUE TITLE
Some snippets not being converted.

### ISSUE THREAD

**Issue by safield** [kevinlinxp/intellij-sublime-snippets-support#2]
I have the following sublime snippet folder structure....

User
    Snippets
        MySnippets

It contains snippets for xml and c++.

The xml snippets are properly being converted whereas the C++ ones are not.

When I go into the Plugin settings, both the xml and C++ snippets path are listed in the window of imported snippets.

The C++ ones do not show up in the SublimeSnippets.xml output file.

I have attached examples of a working xml snippet and a not working c++ one.

[c++_foo.zip](https://github.com/kevinlinxp/intellij-sublime-snippets-support/files/2691626/c%2B%2B_foo.zip)

**Comment by kevinlinxp** [comment]
Hi @safield, thank you very much for reporting this issue. I've committed a fix [74adb388a659aa6cb339f003b7a771afb1b7561f](https://github.com/kevinlinxp/intellij-sublime-snippets-support/commit/74adb388a659aa6cb339f003b7a771afb1b7561f) for it and published v1.2.5. You can download the new version now.
