### ISSUE TITLE
not working in PyCharm Community Edition 2020.3.4 x64

### ISSUE THREAD

**Issue by bksubramanyarao** [kevinlinxp/intellij-sublime-snippets-support#7]
hello,

please change
SOURCE_PYTHON("source.python", "PYTHON"),
to
SOURCE_PYTHON("source.python", "Python"),
in
https://github.com/kevinlinxp/intellij-sublime-snippets-support/blob/master/src/main/kotlin/com/kevinlinxp/sublimeSnippetsSupport/SublimeSnippetScope.kt

hopefully this will fix the problem
thanks

**Comment by kevinlinxp** [comment]
Thanks very much @bksubramanyarao for letting me know the issue and sorry for this late reply.

Do you know if it can work on other versions of PyCharm and only break in Community Edition 2020.3.4 x64, or it's just some of the versions got this issue?

Many thanks again for your patient.

**Comment by bksubramanyarao** [comment]
@kevinlinxp Thanks for the reply and for this awesome plugin which has helped me a lot.

Based on my memory it was working fine on 19+

As I have mentioned I manually made the changes so now it's working for me, so I just wanted to let you know

Thanks for your contribution on keeping this plugin alive

**Comment by kevinlinxp** [comment]
Many thanks @bksubramanyarao and very glad to hear the plugin is useful for you :)

I've fixed the python not working issue with release 1.3.0. It's already submitted for JetBrains' review and should be downloadable within 2 business days or so. It works for IDEs from 2019.3 and above.

The new release also uses the platform's latest APIs to avoid being impacted by a breaking change in 2021.3.

Please kindly let me know if any more issues found.

Regards,
Kevin

**Comment by bksubramanyarao** [comment]
@kevinlinxp i tested the new release 1.3.0 and it is working fine in pycharm and phpstorm

Once again thanks for all the contribution you have done for this plugin.
In future looking forward to contribute once I learn kotlin

Regards
Subramanya

**Comment by kevinlinxp** [comment]
Thanks very much for confirming the new version works @bksubramanyarao, and It's great to hear you are interested to be a contributor. I look forward to work with you to bring more features to the plugin in future :D
